apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: devops-lab
  namespace: argocd

spec:

  description: DevOps portfolio project

  sourceRepos:
    - "*"

  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"