name: Kubernetes Deploy Test


on:

  workflow_call:


jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:


      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest


      - name: Verify cluster

        run: |

          kubectl get nodes

          kubectl cluster-info


      - name: Setup Helm

        uses: azure/setup-helm@v4


      - name: Helm install

        run: |

          helm upgrade --install kpractice \
          ./helm/nginx-chart \
          --namespace kpractice \
          --create-namespace


      - name: Check resources

        run: |

          kubectl get all -n kpractice


      - name: Check pods

        run: |

          kubectl wait \
          --for=condition=ready pod \
          --all \
          -n kpractice \
          --timeout=120s