name: Kubernetes Deploy


on:

  workflow_call:


jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:


      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup kubectl
        uses: azure/setup-kubectl@v4


      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          printf '%s' "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config


      - name: Test kubectl connection
        run: |
          kubectl cluster-info
          kubectl get nodes


      - name: Setup Helm
        uses: azure/setup-helm@v4


      - name: Deploy Helm chart
        run: |
          helm upgrade --install kpractice \
          ./helm/nginx-chart \
          --namespace kpractice \
          --create-namespace