name: Docker Build

on:
  push:
    branches:
      - main
    paths:
      - "docker/**"
      - ".github/workflows/docker-build.yaml"

  pull_request:
    branches:
      - main
    paths:
      - "docker/**"

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t kpractice-app ./docker/nginx

      - name: Show Docker images
        run: docker images