name: Kpractice CI/CD


on:

  push:

    branches:
      - main


permissions:

  contents: read

  packages: write



jobs:


  docker-release:

    uses: ./.github/workflows/docker-release.yaml



  terraform-check:

    uses: ./.github/workflows/terraform-check.yaml



  kubernetes-check:

    uses: ./.github/workflows/kubernetes-check.yaml



  deploy:

    needs:

      - docker-release
      - terraform-check
      - kubernetes-check


    uses: ./.github/workflows/deploy.yaml


    secrets: inherit