name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t kpractice:${GITHUB_REF_NAME} ./docker

      - name: Show Image
        run: docker images